/**
 * OpenRTB 2.5 No-Bid Reason Codes
 * Signals why a bidder did not offer a bid for the impression
 */
export const NoBidReasonCode = {
  UNKNOWN_ERROR: 0,
  TECHNICAL_ERROR: 1,
  INVALID_REQUEST: 2,
  KNOWN_WEB_SPIDER: 3,
  SUSPECTED_NON_HUMAN_TRAFFIC: 4,
  CLOUD_DATA_CENTER_OR_PROXY_IP: 5,
  UNSUPPORTED_DEVICE: 6,
  BLOCKED_PUBLISHER_OR_SITE: 7,
  UNMATCHED_USER: 8,
  DAILY_READER_CAP_MET: 9,
  DAILY_DOMAIN_CAP_MET: 10,
} as const;
export type NoBidReasonCode =
  (typeof NoBidReasonCode)[keyof typeof NoBidReasonCode];

/**
 * OpenRTB 2.5 Loss Reason Codes
 * Informs a bidder why they did not win an impression
 */
export const LossReasonCode = {
  // Standard Results
  BID_WON: 0,
  INTERNAL_ERROR: 1,
  IMPRESSION_OPPORTUNITY_EXPIRED: 2,
  INVALID_BID_RESPONSE: 3,
  INVALID_DEAL_ID: 4,
  INVALID_AUCTION_ID: 5,
  INVALID_ADVERTISER_DOMAIN: 6,
  MISSING_MARKUP: 7,
  MISSING_CREATIVE_ID: 8,
  MISSING_BID_PRICE: 9,
  MISSING_MINIMUM_CREATIVE_APPROVAL_DATA: 10,

  // Price-Related
  BID_BELOW_AUCTION_FLOOR: 100,
  BID_BELOW_DEAL_FLOOR: 101,
  LOST_TO_HIGHER_BID: 102,
  LOST_TO_PMP_DEAL: 103,
  BUYER_SEAT_BLOCKED: 104,

  // Creative Filtering
  CREATIVE_FILTERED_GENERAL: 200,
  CREATIVE_FILTERED_PENDING_PROCESSING: 201,
  CREATIVE_FILTERED_DISAPPROVED: 202,
  CREATIVE_FILTERED_SIZE_NOT_ALLOWED: 203,
  CREATIVE_FILTERED_INCORRECT_FORMAT: 204,
  CREATIVE_FILTERED_ADVERTISER_EXCLUSIONS: 205,
  CREATIVE_FILTERED_APP_BUNDLE_EXCLUSIONS: 206,
  CREATIVE_FILTERED_NOT_SECURE: 207,
  CREATIVE_FILTERED_LANGUAGE_EXCLUSIONS: 208,
  CREATIVE_FILTERED_CATEGORY_EXCLUSIONS: 209,
  CREATIVE_FILTERED_ATTRIBUTE_EXCLUSIONS: 210,
  CREATIVE_FILTERED_AD_TYPE_EXCLUSIONS: 211,
  CREATIVE_FILTERED_ANIMATION_TOO_LONG: 212,
  CREATIVE_FILTERED_NOT_ALLOWED_IN_PMP_DEAL: 213,

  // Exchange Specific
  EXCHANGE_SPECIFIC: 1000,
} as const;
export type LossReasonCode =
  (typeof LossReasonCode)[keyof typeof LossReasonCode];
